### ISSUE TITLE
Dead link detection

### ISSUE THREAD

**Issue by sesquipedalianman** [sebsauvage/Shaarli#218]
I would love to have a way to determine what links I have which are now dead.  There are link checker add-ins for browsers.  Would it be possible to have something like that in shaarli, or does anyone have a simple idea of how to do this?

**Comment by nodiscc** [comment]
Hi @sesquipedalianman this repository is currently unmaintained, see https://github.com/sebsauvage/Shaarli/issues/191 -> https://github.com/shaarli/Shaarli. We will not add this to Shaarli, because I think batch operations like this have to be done outside of Shaarli. There is little interest in letting the server do this job, it can be done by a client form a bookmarks export. Moreover how do you detect "dead links"? 404 errors? A lot of sites return 200s or 302 for missing pages. Some links will appear as valid, but the content will have been removed.

For a batch archival/checking tool, see https://github.com/nodiscc/shaarchiver/tree/rewrite, https://github.com/nodiscc/shaarchiver/issues/1.

Feel free to close this issue (it will not be fixed here as the maintainer has stated he would not update shaarli for some time)

**Comment by sesquipedalianman** [comment]
Valid points @nodiscc.  Thanks for the reply
