### ISSUE TITLE
Make Shaarli a Sandstorm.io app

### ISSUE THREAD

**Issue by jibe-b** [sebsauvage/Shaarli#230]
Hi!

Shaarli is a nice software that deserve wider spread, according to me.

Do you know sandstorm.io? I think Shaarli should be added to the apps list.
The concept is to enable existing open source apps to run inside the sandstorm server app, the steps to do it are documented here: https://docs.sandstorm.io/en/latest/developing/

And I noticed that there people who add a bookmark of sandstorm.io inside their Shaarli ;)

http://jcfrog.com/shaarli41/?zGRDiw
http://nicolasmd.com.ar/links/?VQVcRA
http://dotmana.com/shaarli/?IbD6Cg
https://shaa.cicogna.fr/?searchtags=sandstorm
http://river.hoa.ro/search.php?q=tag:personal
http://shaarli.claire-desbois.fr/?searchterm=sandstorm

Best regards

**Comment by mro** [comment]
@jibe-b can you explain to me what `.io` stands for?

**Comment by jibe-b** [comment]
@mro It's the Domain Name extension for Indian Ocean[[1]](http://nic.io/). And it has become a trend as it also means input/output, it seems. But the sandstorm leading team works in Palo Alto[[2]](https://sandstorm.io/about).

[1]: .io domain name organisation: http://nic.io/
[2]: https://sandstorm.io/about .

**Comment by nodiscc** [comment]
Hi @jibe-b 

1 - This repository is unmaintained

> Note: I do not have enough time to maintain this project right now. You will find a more up-to-date fork of this project at https://github.com/shaarli/Shaarli. Please use this fork for requests/bug/latest updates...

2 - You can always ask for this on https://github.com/shaarli/Shaarli, but I'd prefer avoiding storing resources for third-party projects (https://docs.sandstorm.io/en/latest/vagrant-spk/packaging-tutorial/ `.sandstorm` file for example) in the Shaarli repository itself. Otherwise we'll end up with a lot of unrelated files for various third-party systems (sandstorm, vagrant, docker, ansible... etc etc etc) If you want to maintain a sandstorm Shaarli package, you can do so in your own repository and we'll gladly link to from the [wiki](https://github.com/shaarli/Shaarli/wiki).

**Comment by jibe-b** [comment]
Ah, right, I thought I was on the shaarli/Shaarli repo. I'll ask there.

That's meaningful to store it in a separated repository.

**Comment by jibe-b** [comment]
Sandstorm development has changed ([blog article](https://sandstorm.io/news/2017-02-06-sandstorm-returning-to-community-roots)) and the attempts made in https://github.com/shaarli/Shaarli/issues/499 were unsuccesful.
